INSERT INTO public.project (id, name, project_owner_id) VALUES (20, 'Inbox', 10);
INSERT INTO public.project (id, name, project_owner_id) VALUES (23, 'Vyhrnout sníh', 11);
INSERT INTO public.project (id, name, project_owner_id) VALUES (24, 'Otevřít okno', 1);
INSERT INTO public.project (id, name, project_owner_id) VALUES (25, 'Vyměnit olej v autě', 18);
INSERT INTO public.project (id, name, project_owner_id) VALUES (26, 'Přezout na zimu', 13);
INSERT INTO public.project (id, name, project_owner_id) VALUES (27, 'Umýt nádobí', 12);
INSERT INTO public.project (id, name, project_owner_id) VALUES (28, 'Securita II', 11);
INSERT INTO public.project (id, name, project_owner_id) VALUES (29, 'Napsat diplomku', 10);
INSERT INTO public.project (id, name, project_owner_id) VALUES (21, 'NASA', 16);
INSERT INTO public.project (id, name, project_owner_id) VALUES (22, 'GTB', 17);